swagger: '2.0'
info:
    title: Users API
    description: Serverless users Rest API
    version: '0.1'
schemes:
    - https
produces:
    - application/json
paths:
    /healthcheck:
        get:
            operationId: healthcheck
            summary: Healthcheck endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
            responses:
                200:
                    description: Healthcheck success response

    /users:
        get:
            operationId: get-users
            summary: Get users sorted by creation date descending and paginated
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
                deadline: 60.0
            parameters:
                - name: lastCreatedAt
                  in: query
                  type: string
                  description: When paginating this is the createdAt value of the last user received
                - name: limit
                  in: query
                  type: string
                  description: Maximum number of users to return (defaults to 20)
            responses:
                200:
                    description: GET user success
                    schema:
                        type: object
                422:
                    description: Error retrieving users
                    schema:
                        type: object
        post:
            operationId: post-user
            summary: POST user endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
                deadline: 60.0
            parameters:
                - name: user
                  in: body
                  description: User to create
                  schema:
                      type: object
                      required:
                          - name
                          - email
                      properties:
                          name:
                              type: string
                          email:
                              type: string
            responses:
                200:
                    description: POST user success
                400:
                    description: Error
                    schema:
                        type: object
        options:
            operationId: options-users
            summary: CORS preflight endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
            responses:
                204:
                    description: CORS preflight success
    /users/{userId}:
        get:
            operationId: get-user
            summary: GET user endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
                deadline: 60.0
            parameters:
                - name: userId
                  in: path
                  required: true
                  type: string
            responses:
                200:
                    description: GET user success
                422:
                    description: Error retrieving one user
                    schema:
                        type: object
        # put:
        #     operationId: put-user
        #     summary: PUT user endpoint
        #     x-google-backend:
        #         address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
        #         deadline: 60.0
        #     parameters:
        #         - name: userId
        #           in: path
        #           required: true
        #           type: string
        #         - name: user
        #           in: body
        #           description: User to update
        #           schema:
        #               type: object
        #               properties:
        #                   name:
        #                       type: string
        #                   email:
        #                       type: string
        #     responses:
        #         200:
        #             description: PUT user success
        #         400:
        #             description: Error
        #             schema:
        #                 type: object
        delete:
            operationId: delete-user
            summary: DELETE user endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
                deadline: 60.0
            parameters:
                - name: userId
                  in: path
                  required: true
                  type: string
            responses:
                200:
                    description: DELETE user success
                422:
                    description: Error deleting user
                    schema:
                        type: object
        options:
            operationId: options-client-by-id
            summary: CORS preflight endpoint
            x-google-backend:
                address: https://us-east1-sample-ms-soffredi.cloudfunctions.net/users-api-marcelo
            parameters:
                - name: userId
                  in: path
                  required: true
                  type: string
            responses:
                204:
                    description: CORS preflight success
